test_that("ETL validation", {

  # Set the environment to test schemas to allow functions that reference
  # the environment to access the correct schema
  amsterdaumcdb_test_schema <- "amsterdamumcdb_test"
  cdm_test_schema <- "cdm_test"
  amstel_env$config$databases$amsterdamumcdb$schema <- amsterdaumcdb_test_schema
  amstel_env$config$databases$cdm$schema <- cdm_test_schema

  # Create connections to both schemas
  adb_connection_details <- get_connection_details("amsterdamumcdb")
  adb_conn <- DatabaseConnector::connect(adb_connection_details)
  on.exit(DatabaseConnector::disconnect(adb_conn), add = TRUE)

  cdm_connection_details <- get_connection_details("cdm")
  cdm_conn <- DatabaseConnector::connect(cdm_connection_details)
  on.exit(DatabaseConnector::disconnect(cdm_conn), add = TRUE)

  # Create a clean AmsterdamUMCdb test schema with empty test tables
  log_info("Creating AmsterdamUMCdb test schema and tables...")
  sql <- "CREATE SCHEMA IF NOT EXISTS @amsterdamumcdb_schema;"
  DatabaseConnector::renderTranslateExecuteSql(
    connection = adb_conn,
    sql = sql,
    amsterdamumcdb_schema = amsterdaumcdb_test_schema
    )
  sql <- load_sql('create_amsterdamumcdb_tables.sql')
  DatabaseConnector::renderTranslateExecuteSql(
    connection = adb_conn,
    sql = sql,
    amsterdamumcdb_schema = amsterdaumcdb_test_schema
    )

  # Uses the (modified) TestFramework generated by RabbitInAHat and sets up
  # tests for the CDM tables
  log_info("Setting up test data and tests...")
  source(test_path("AmsterdamUMCdb-TestFramework.R"))

  ### Person ###
  declareTest(101, "Person id")
  add_admissions(patientid = 101, admissionid = 1101)
  add_admissions(patientid = 101, admissionid = 1102)
  expect_person(person_id = 101, person_source_value = 101)

  declareTest(102, "Person gender mappings")
  add_admissions(patientid = 102, admissionid = 3, gender = "Man")
  add_admissions(patientid = 112, admissionid = 4, gender = "Vrouw")
  expect_person(person_id = 102, gender_concept_id = 8507,
                gender_source_value = "Man")
  expect_person(person_id = 112, gender_concept_id = 8532,
                gender_source_value = "Vrouw")

  declareTest(103, "Person year of birth")
  add_admissions(patientid = 103, admissionid = 1103, agegroup = "60-69",
                 admissionyeargroup = '2010-2016')
  # calculated: 2013 - 65 = 1948
  expect_person(person_id = 103, year_of_birth = 1948)

  ### Visit_occurrence ###
  declareTest(201, "Visit_occurrence id")
  expect_visit_occurrence(visit_occurrence_id = 1101, person_id = 101)
  expect_visit_occurrence(visit_occurrence_id = 1102, person_id = 101)

  declareTest(202, "Visit_occurrence visit_concept ICU")
  expect_visit_occurrence(visit_occurrence_id = 1101, person_id = 101,
                          visit_concept_id = 32037)

  declareTest(203, "Visit_occurrence visit_start_date")
  add_admissions(admissionid = 1203, patientid = 203,
                 admissionyeargroup = '2010-2016')
  expect_visit_occurrence(person_id = 203, visit_occurrence_id = 1203,
                          visit_start_date = '2013-01-01')

  ### Observation_period ###
  declareTest(301, "Observation_period person_id")
  add_admissions(patientid = 301, admissionid = 1301, admissioncount = 1,
                 admissionyeargroup = '2003-2009', admittedat = 0,
                 dischargedat = 3*24*60*60*1000)
  expect_observation_period(person_id = 301,
                            observation_period_start_date = '2006-01-01',
                            observation_period_end_date = '2006-01-04')

  declareTest(302, "Observation_period start_date / end_date")
  add_admissions(patientid = 302, admissionid = 1302, admissioncount = 1,
                 admissionyeargroup = '2003-2009', admittedat = 0,
                 dischargedat = 20*24*60*60*1000)
  expect_observation_period(person_id = 302,
                            observation_period_start_date = '2006-01-01',
                            observation_period_end_date = '2006-01-21')


  ### Location ###
  declareTest(401, "Location Amsterdam UMC")
  expect_location(location_id = 1, address_1 = "De Boelelaan 1117")

  ### Care site ###
  declareTest(501, "Care_site Intensive Care unit")
  expect_care_site(care_site_id = 1, care_site_name = "Intensive Care",
                   place_of_service_concept_id = 581379)

  declareTest(502, "Care_site Medium Care unit")
  expect_care_site(care_site_id = 2, care_site_name = "Medium Care",
                   place_of_service_concept_id = 581379)

  ### Condition occurrence ###
  declareTest(601, "condition_occurrence reason for admission")
  add_admissions(patientid = 601, admissionid = 1601)
  add_listitems(admissionid = 1601, itemid = 13116, valueid = 1)
  expect_condition_occurrence(person_id = 601, condition_concept_id = 317576,
                              condition_status_concept_id = 32901)

  ### Death ###
  declareTest(701, "death person_id")
  add_admissions(patientid = 701, admissionid = 1701,
                 dateofdeath = 14*24*60*60*1000)
  expect_death(person_id = 701)
  declareTest(702, "death no death")
  add_admissions(patientid = 702, admissionid = 1702, dateofdeath = NULL)
  expect_no_death(person_id = 702)
  declareTest(703, "death 14 days after admission")
  add_admissions(patientid = 703, admissionid = 1703, admittedat = 0,
                 admissionyeargroup = '2010-2016',
                 dateofdeath = 14*24*60*60*1000)
  expect_death(person_id = 703, death_date = '2013-01-15')

  ### Procedure occurrence ###
  declareTest(801, "procedure_occurence person_id")
  add_admissions(patientid = 801, admissionid = 1801)
  add_procedureorderitems(admissionid = 1801)
  expect_procedure_occurrence(person_id = 801)

  declareTest(802, "procedure_occurence checking procedure concept")
  add_admissions(patientid = 802, admissionid = 1802)
  add_procedureorderitems(admissionid = 1802, itemid = 13021)
  expect_procedure_occurrence(person_id = 802, procedure_concept_id = 44791813)

  ### Measurement ###
  declareTest(901, "measurement person_id")
  add_admissions(patientid = 901, admissionid = 1901)
  add_numericitems(admissionid = 1901, itemid = 6640)

  declareTest(902, "measurement mapping heart rate.beat-to-beat by EKG")
  add_admissions(patientid = 902, admissionid = 1902)
  add_numericitems(admissionid = 1902, itemid = 6640)
  expect_measurement(person_id = 902, measurement_concept_id = 21490872)

  declareTest(903, "measurement mapping ultrafiltrate volume removed")
  add_admissions(patientid = 903, admissionid = 1903)
  add_numericitems(admissionid = 1903, itemid = 20079)
  expect_measurement(person_id = 903, measurement_concept_id = 1988590)

  ### Observation ###
  declareTest(1001, "observation person_id")
  add_admissions(patientid = 1001, admissionid = 11001)
  add_listitems(admissionid = 11001, itemid = 6671)
  expect_observation(person_id = 1001)

  declareTest(1002, "observation mapping Cardiac rhythm type")
  add_admissions(patientid = 1002, admissionid = 11002)
  add_listitems(admissionid = 11002, itemid = 6671)
  expect_observation(person_id = 1002, observation_concept_id = 4091457)

  declareTest(1003, "observation mapping value_as_concept Sinustachycardia")
  add_admissions(patientid = 1003, admissionid = 11003)
  add_listitems(admissionid = 11003, itemid = 6671, valueid = 21)
  expect_observation(person_id = 1003, observation_concept_id = 4091457,
                     value_as_concept_id = 45879290)

  ### Drug_exposure ###
  declareTest(1101, "drug_exposure person_id")
  add_admissions(patientid = 1101, admissionid = 11101)
  add_drugitems(admissionid = 11101)
  expect_drug_exposure(person_id = 1101)

  declareTest(1102, "drug_exposure mapping propofol")
  add_admissions(patientid = 1102, admissionid = 11102)
  add_drugitems(admissionid = 11102, itemid = 7480, ordercategoryid = 65)
  expect_drug_exposure(person_id = 1102, drug_concept_id = 36896005)

  declareTest(1103, "drug_exposure quantity propofol")
  add_admissions(patientid = 1103, admissionid = 11103)
  add_drugitems(admissionid = 11103, itemid = 7480, ordercategoryid = 65,
                rate = 10, # 10 ml/hour
                rateunitid = 6, # ml
                ratetimeunitid = 5, # hour
                dose = 200, # 200 mg/hour
                doseunitid = 10, # mg
                doserateunitid = 5, # hour
                administered = 400, # 400 mg
                administeredunitid = 10 # mg
  )
  expect_drug_exposure(person_id = 1103, drug_concept_id = 36896005,
                       quantity = 400)

  declareTest(1104, "drug_exposure fluidin")
  add_admissions(patientid = 1104, admissionid = 11104)
  add_drugitems(admissionid = 11104, itemid = 7480, fluidin = 50)
  expect_measurement(measurement_concept_id = 3037253, # fluid intake
                     value_as_number = 50)

  ### Device_exposure ###
  declareTest(1201, "device_exposure person_id")
  add_admissions(patientid = 1201, admissionid = 11201)
  add_processitems(admissionid = 11201)

  declareTest(1202, "device_exposure mapping endotracheal tube")
  add_admissions(patientid = 1202, admissionid = 11202)
  add_processitems(admissionid = 11202, itemid = 12634)
  expect_device_exposure(person_id = 1202, device_concept_id = 4097216)

  ### Specimen ###
  declareTest(1301, "specimen person_id")
  add_admissions(patientid = 1301, admissionid = 11301)
  add_processitems(admissionid = 11301)

  declareTest(1302, "specimen mapping freetextitems ART.")
  add_admissions(patientid = 1302, admissionid = 11302)
  add_freetextitems(admissionid = 11302, itemid = 11646, value = 'ART.')
  expect_specimen(person_id = 1302,
                  specimen_concept_id = 4047496, # arterial blood specimen
                  specimen_type_concept_id = 32856 # Lab
                  )

  # Inserts test data into the AmsterdamUMCdb test tables
  log_info("Inserting test data into AmsterdamUMCdb test tables...")
  insert_sql <- paste(generateInsertSql(databaseSchema = "@amsterdamumcdb_schema"),
                      collapse = "\n")
  DatabaseConnector::renderTranslateExecuteSql(
    connection = adb_conn,
    sql = insert_sql,
    amsterdamumcdb_schema = amsterdaumcdb_test_schema
  )

  log_info("Running ETL...")

  # runs the ETL but without re-creating the vocabularies,
  # running Achilles or DataQualityDashboard
  etl(vocabulary = FALSE, mappings = FALSE,
      achilles = FALSE, dqd = FALSE)

  # Run checks based on records created by ETL
  log_info("Checking output...")
  test_sql <- paste(generateTestSql(databaseSchema = "@cdm_schema"),
                   collapse = "\n")

  DatabaseConnector::renderTranslateExecuteSql(
    connection = cdm_conn,
    sql = test_sql,
    cdm_schema = cdm_test_schema
  )

  # Get test results
  test_results_sql <- "SELECT * FROM @cdm_schema.test_results"
  test_results <- DatabaseConnector::renderTranslateQuerySql(
    connection = cdm_conn,
    sql = test_results_sql,
    cdm_schema = cdm_test_schema
  )

  for(i in 1:nrow(test_results)) {
    log_info(paste0(
      '\nTest ',
      test_results[i, 'ID'],
      '-',
      test_results[i, 'DESCRIPTION'],
      ':'
    ))
    status <- test_results[i, 'STATUS']
    expect_equal(status, 'PASS')
  }
})


