test_that("ETL validation", {

  # Set the environment to test schemes to allow functions that reference
  # the environment to access the correct schema
  amsterdaumcdb_test_schema <- "amsterdamumcdb_test"
  cdm_test_schema <- "cdm_test"

  connections = create_environment(name="test")
  adb_conn = connections$adb_conn
  cdm_conn = connections$cdm_conn
  on.exit(DatabaseConnector::disconnect(adb_conn), add = TRUE)
  on.exit(DatabaseConnector::disconnect(cdm_conn), add = TRUE)

  # reset environment to defaults
  on.exit(amstel_env$config <- get_config(), add = TRUE)

  # Uses the (modified) TestFramework generated by RabbitInAHat and sets up
  # tests for the CDM tables
  log_info("Setting up test data and tests...")
  source(test_path("AmsterdamUMCdb-TestFramework.R"))

  ### Person ###
  declareTest(101, "Person id")
  add_admissions(patientid = 101, admissionid = 1101)
  add_admissions(patientid = 101, admissionid = 1102)
  expect_person(person_id = 101, person_source_value = 101)

  declareTest(102, "Person gender mappings")
  add_admissions(patientid = 102, admissionid = 3, gender = "Man")
  add_admissions(patientid = 112, admissionid = 4, gender = "Vrouw")
  expect_person(person_id = 102, gender_concept_id = 8507,
                gender_source_value = "Man")
  expect_person(person_id = 112, gender_concept_id = 8532,
                gender_source_value = "Vrouw")

  declareTest(103, "Person year of birth")
  add_admissions(patientid = 103, admissionid = 1103, agegroup = "60-69",
                 admissionyeargroup = '2010-2016')
  # calculated: 2013 - 65 = 1948
  expect_person(person_id = 103, year_of_birth = 1948)

  ### Visit_occurrence ###
  declareTest(201, "Visit_occurrence id")
  expect_visit_occurrence(visit_occurrence_id = 1101, person_id = 101)
  expect_visit_occurrence(visit_occurrence_id = 1102, person_id = 101)

  declareTest(202, "Visit_occurrence visit_concept ICU")
  expect_visit_occurrence(visit_occurrence_id = 1101, person_id = 101,
                          visit_concept_id = 32037)

  declareTest(203, "Visit_occurrence visit_start_date")
  add_admissions(admissionid = 1203, patientid = 203,
                 admissionyeargroup = '2010-2016')
  expect_visit_occurrence(person_id = 203, visit_occurrence_id = 1203,
                          visit_start_date = '2013-01-01')

  ### Observation_period ###
  declareTest(301, "Observation_period person_id")
  add_admissions(patientid = 301, admissionid = 1301, admissioncount = 1,
                 admissionyeargroup = '2003-2009', admittedat = 0,
                 dischargedat = 3*24*60*60*1000)
  expect_observation_period(person_id = 301,
                            observation_period_start_date = '2006-01-01',
                            observation_period_end_date = '2006-01-04')

  declareTest(302, "Observation_period start_date / end_date")
  add_admissions(patientid = 302, admissionid = 1302, admissioncount = 1,
                 admissionyeargroup = '2003-2009', admittedat = 0,
                 dischargedat = 20*24*60*60*1000)
  expect_observation_period(person_id = 302,
                            observation_period_start_date = '2006-01-01',
                            observation_period_end_date = '2006-01-21')


  ### Location ###
  declareTest(401, "Location Amsterdam UMC")
  expect_location(location_id = 1, address_1 = "De Boelelaan 1117")

  ### Care site ###
  declareTest(501, "Care_site Intensive Care unit")
  expect_care_site(care_site_id = 1, care_site_name = "Intensive Care",
                   place_of_service_concept_id = 581379)

  declareTest(502, "Care_site Medium Care unit")
  expect_care_site(care_site_id = 2, care_site_name = "Medium Care",
                   place_of_service_concept_id = 581379)

  ### Condition occurrence ###
  declareTest(601, "condition_occurrence reason for admission")
  add_admissions(patientid = 601, admissionid = 1601)
  add_listitems(admissionid = 1601, itemid = 13116, valueid = 1)
  expect_condition_occurrence(person_id = 601, condition_concept_id = 317576,
                              condition_status_concept_id = 32901)

  ### Death ###
  declareTest(701, "death person_id")
  add_admissions(patientid = 701, admissionid = 1701,
                 dateofdeath = 14*24*60*60*1000)
  expect_death(person_id = 701)
  declareTest(702, "death no death")
  add_admissions(patientid = 702, admissionid = 1702, dateofdeath = NULL)
  expect_no_death(person_id = 702)
  declareTest(703, "death 14 days after admission")
  add_admissions(patientid = 703, admissionid = 1703, admittedat = 0,
                 admissionyeargroup = '2010-2016',
                 dateofdeath = 14*24*60*60*1000)
  expect_death(person_id = 703, death_date = '2013-01-15')

  ### Procedure occurrence ###
  declareTest(801, "procedure_occurence person_id")
  add_admissions(patientid = 801, admissionid = 1801)
  add_procedureorderitems(admissionid = 1801)
  expect_procedure_occurrence(person_id = 801)

  declareTest(802, "procedure_occurence checking procedure concept")
  add_admissions(patientid = 802, admissionid = 1802)
  add_procedureorderitems(admissionid = 1802, itemid = 13021)
  expect_procedure_occurrence(person_id = 802, procedure_concept_id = 44791813)

  # some listitems contain information about the number of times a procedure has
  # been performed. Unfortunately, we cannot directly use the valueid since
  # this does not always correspond with the quantity. The ETL converts the
  # text value to a numeric one.
  declareTest(803, "procedure_occurence quantity from text value listitems")
  add_admissions(patientid = 803, admissionid = 1803)
  add_listitems(
    admissionid = 1803,
    item = "Aantal Bronchiaaltoilet",
    itemid = 8889,
    valueid = 8,
    value = "8x"
  )

  expect_procedure_occurrence(
    person_id = 803,
    procedure_concept_id = 4239191,
    quantity = 8,
    procedure_source_value = "Aantal Bronchiaaltoilet",
    modifier_source_value = "8x"
  )

  # some listitems values have been explicitly mapped to 'Performed' or
  # 'Not Performed' and should be converted to 1 or 0 respectively.
  declareTest(804, "procedure_occurence quantity mapped to 1")
  add_admissions(patientid = 804, admissionid = 1804)

  add_listitems(
    admissionid = 1804,
    item = "Mond/Keel toilet",
    itemid = 8892,
    value = "Gedaan",
    valueid = 1,
  )

  expect_procedure_occurrence(
    person_id = 804,
    procedure_concept_id = 4301571,
    quantity = 1,
    procedure_source_value = "Mond/Keel toilet",
    modifier_source_value = "Gedaan"
  )

  # procedures that were documented as not have taken place should not be
  # inserted in the procedure_occurrence table, though they are temporarily
  # inserted in stem_table
  declareTest(805, "procedure_occurence ignore quantity = 0")
  add_admissions(patientid = 805, admissionid = 1805)
  add_listitems(
    admissionid = 1805,
    item = "Mond/Keel toilet",
    itemid = 8892,
    value = "Niet Gedaan",
    valueid = 2,
  )
  expect_no_procedure_occurrence(quantity = 0)

  # procedures with quantity = NULL should be inserted correctly
  declareTest(806, "procedure_occurence allow quantity = NULL")
  add_admissions(patientid = 806, admissionid = 1806)
  add_listitems(
    admissionid = 1806,
    item = "Intubatie Techniek",
    itemid = 14577,
    value = "Glidescoop",
    valueid = 2,
  )
  expect_procedure_occurrence(
    procedure_concept_id = 4202832,
    quantity = NULL,
    procedure_source_value = "Intubatie Techniek",
    modifier_concept_id = 40492457,
    modifier_source_value = "Glidescoop"
  )

  ### Measurement ###
  declareTest(901, "measurement person_id")
  add_admissions(patientid = 901, admissionid = 1901)
  add_numericitems(admissionid = 1901, itemid = 6640)

  declareTest(902, "measurement mapping heart rate.beat-to-beat by EKG")
  add_admissions(patientid = 902, admissionid = 1902)
  add_numericitems(admissionid = 1902, itemid = 6640)
  expect_measurement(person_id = 902, measurement_concept_id = 21490872)

  declareTest(903, "measurement mapping ultrafiltrate volume removed")
  add_admissions(patientid = 903, admissionid = 1903)
  add_numericitems(admissionid = 1903, itemid = 20079)
  expect_measurement(person_id = 903, measurement_concept_id = 1988590)

  declareTest(904, "measurement default unit")
  add_admissions(patientid = 904, admissionid = 1904)
  add_numericitems(admissionid = 1904, itemid = 6640,
                   item = "Hartfrequentie",
                   value = 84,
                   unitid = 15,
                   unit = "/min")
  # expect '/min'
  expect_measurement(person_id = 904,
                     measurement_concept_id = 21490872,
                     unit_concept_id = 8541)

  declareTest(905, "measurement numeric corrected unit ")
  add_admissions(patientid = 905, admissionid = 1905)
  add_numericitems(admissionid = 1905,
                   itemid = 6709,
                   item = "Saturatie (Monitor)",
                   value = 96,
                   unitid = 0,
                   unit = "None")

  # correct 'None' to 'Percent'. Since the `unit_source_concept_id` will be
  # used in future ETLs to convert source to 'preferred'  units store that
  # correct unit there as well
  expect_measurement(person_id = 905,
                     measurement_concept_id = 40762499,
                     unit_source_concept_id = 8554,
                     unit_concept_id = 8554)

  declareTest(906, "measurement value")
  add_admissions(patientid = 906, admissionid = 1906)
  add_numericitems(admissionid = 1906,
                   itemid = 6709,
                   item = "Saturatie (Monitor)",
                   value = 96,
                   unitid = 0,
                   unit = "None")
  expect_measurement(person_id = 906,
                     measurement_concept_id = 40762499,
                     unit_concept_id = 8554,
                     value_as_number = 96)

  declareTest(907, "measurement laboratory")
  add_admissions(patientid = 907, admissionid = 1907)
  add_numericitems(admissionid = 1907,
                   itemid = 9996,
                   item = "PO2 (bloed)",
                   value = 71,
                   unitid = 173,
                   unit = "mmHg",
                   islabresult = 1,
                   fluidout = NULL)
  expect_measurement(person_id = 907,
                     measurement_concept_id = 3027315,
                     value_as_number = 71)

  # correct missing or invalid units ('None'/'Geen')
  # test 'Geen' -> 'Percent'
  declareTest(908, "measurement laboratory corrected unit")
  add_admissions(patientid = 908, admissionid = 1908)
  add_numericitems(admissionid = 1908,
                   itemid = 11850,
                   item = "Monocyten % (bloed)",
                   value = 5,
                   unitid = 0,
                   unit = "Geen",
                   islabresult = 1,
                   fluidout = NULL)
  expect_measurement(person_id = 908,
                     measurement_concept_id = 3019069,
                     unit_source_concept_id = 8554,
                     unit_concept_id = 8554)


  # For measurements without unit ('None'/'Geen') unit_concept_id needs to
  # be NULL (not 0)
  declareTest(909, "measurement laboratory without unit: 191 (Geen)")
  add_admissions(patientid = 909, admissionid = 1909)
  add_numericitems(admissionid = 1909, itemid = 11545,
    item = "Ht(v.Bgs) (bloed)", tag = " ",
    value = 0.23999999, unitid = 191, unit = "Geen",
    measuredat = 20520000,
    registeredat = 22320000,
    registeredby = "ICV_IC-Verpleegkundig",
    updatedat = 22376384,
    updatedby = "ICV_IC-Verpleegkundig",
    islabresult = 1,
    fluidout = NULL)
  expect_measurement(person_id = 909, measurement_concept_id = 42869588,
                     unit_concept_id = NULL)
  expect_no_measurement(measurement_concept_id = 42869588,
                     unit_concept_id = 0)

  declareTest(910, "measurement laboratory without unit: 0 (None)")
  add_admissions(patientid = 910, admissionid = 1910)
  add_numericitems(admissionid = 1910, itemid = 6848,
                   item = "pH", value = 6.98, unitid = 0, unit = "None")
  expect_measurement(person_id = 910, measurement_concept_id = 3010421,
                     unit_concept_id = NULL)
  expect_no_measurement(measurement_concept_id = 3010421,
                        unit_concept_id = 0)

  ### Observation ###
  declareTest(1001, "observation person_id")
  add_admissions(patientid = 1001, admissionid = 11001)
  add_listitems(admissionid = 11001, itemid = 6671)
  expect_observation(person_id = 1001)

  declareTest(1002, "observation mapping Cardiac rhythm type")
  add_admissions(patientid = 1002, admissionid = 11002)
  add_listitems(admissionid = 11002, itemid = 6671)
  expect_observation(person_id = 1002, observation_concept_id = 4091457)

  declareTest(1003, "observation mapping value_as_concept Sinustachycardia")
  add_admissions(patientid = 1003, admissionid = 11003)
  add_listitems(admissionid = 11003, itemid = 6671, valueid = 21)
  expect_observation(person_id = 1003, observation_concept_id = 4091457,
                     value_as_concept_id = 45879290)

  # expect unmapped (or unmappable) concepts to appear in OBSERVATION and not in
  # measurement
  declareTest(1004, "observation unmapped NOT in measurement")
  add_admissions(patientid = 1004, admissionid = 11004)
  add_numericitems(admissionid = 11004, itemid = 12567, item = "WOBv",
                   value = 2.23, unitid = 301, unit = "J/l")
  expect_observation(person_id = 1004, observation_concept_id = 0,
                     value_as_number = 2.23, unit_concept_id = 0)
  expect_no_measurement(person_id = 1004, measurement_concept_id = 0,
                        value_as_number = 2.23, unit_concept_id = 0)

  # unmapped categorical values should be NULL
  declareTest(1005, "observation unmapped values should be NULL")
  add_admissions(patientid = 1005, admissionid = 11005)
  add_listitems(
    admissionid = 11005,
    itemid = 6658,
    item = "IABP Frequentie",
    valueid = 1,
    value = "01:01"
  )

  expect_observation(
    person_id = 1005,
    observation_concept_id = 608009, # Device setting parameter
    value_as_number = NULL,
    value_as_string = "01:01",
    value_as_concept_id = NULL,
    observation_source_value = "IABP Frequentie",
    value_source_value = "01:01"
  )

  declareTest(
    1006,
    "observation shared concepts of discharge destination should be valid"
    )
  add_admissions(patientid = 1006, admissionid = 11006)
  add_listitems(
    admissionid = 11006,
    itemid = 10472,
    item = "Ontslagbestemming",
    valueid = 15,
    value = "VU afdeling SCCH"
  )
  expect_observation(
    person_id = 1006,
    # expect 'Planned discharge destination'
    observation_concept_id = 44810687,
    value_as_number = NULL,
    value_as_string = "VU afdeling SCCH",

    # expect 'Inpatient Cardiac Care Facility' for value_as_concept_id
    value_as_concept_id = 581383
    )

  # converts values of listitems with text values that represent numeric values
  declareTest(1007, "observation numeric text value converted")
  add_admissions(patientid = 1007, admissionid = 11007)
  add_listitems(
    admissionid = 11007,
    itemid = 8691,
    item = "Thoraxdrain1 Zuigkracht",
    valueid = 4,
    value = "- 20 cm H2O"
  )

  expect_observation(
    person_id = 1007,
    observation_concept_id = 4122997,
    value_as_number = -20,
    value_as_string =  "- 20 cm H2O",
    value_as_concept_id = NULL,
    observation_source_value = "Thoraxdrain1 Zuigkracht",
    value_source_value = "- 20 cm H2O"

  )

  # qualifier mapped from MAPPED_TO_TYPE
  declareTest(1008, "observation qualifier mapped from MAPPED_TO_TYPE")
  add_admissions(patientid = 1008, admissionid = 11008)
  add_listitems(
    admissionid = 11008,
    itemid = 6658,
    item = "IABP Frequentie",
    valueid = 1,
    value = "01:01"
  )

  expect_observation(
    person_id = 1008,
    observation_concept_id = 608009, #	Device setting parameter
    value_as_number = NULL,
    value_as_string = "01:01",
    value_as_concept_id = NULL,
    observation_source_value = "IABP Frequentie",
    value_source_value = "01:01",
    qualifier_concept_id = 4044874	# Intra-aortic balloon pump	Device
  )

  ### Drug_exposure ###
  declareTest(1101, "drug_exposure person_id")
  add_admissions(patientid = 1101, admissionid = 11101)
  add_drugitems(admissionid = 11101)
  expect_drug_exposure(person_id = 1101)

  declareTest(1102, "drug_exposure mapping propofol")
  add_admissions(patientid = 1102, admissionid = 11102)
  add_drugitems(admissionid = 11102, itemid = 7480, ordercategoryid = 65)
  expect_drug_exposure(person_id = 1102, drug_concept_id = 36896005)

  declareTest(1103, "drug_exposure quantity propofol")
  add_admissions(patientid = 1103, admissionid = 11103)
  add_drugitems(admissionid = 11103, itemid = 7480, ordercategoryid = 65,
                rate = 10, # 10 ml/hour
                rateunitid = 6, # ml
                ratetimeunitid = 5, # hour
                dose = 200, # 200 mg/hour
                doseunitid = 10, # mg
                doserateunitid = 5, # hour
                administered = 400, # 400 mg
                administeredunitid = 10 # mg
  )
  expect_drug_exposure(person_id = 1103, drug_concept_id = 36896005,
                       quantity = 400)

  declareTest(1104, "drug_exposure fluidin")
  add_admissions(patientid = 1104, admissionid = 11104)
  add_drugitems(admissionid = 11104, itemid = 7480, fluidin = 50)
  expect_measurement(measurement_concept_id = 3037253, # fluid intake
                     value_as_number = 50)

  # Selective Digestive Tract Decontamination is an almost exclusively
  # Dutch ICU method to prevent ventilator-associated pneumonia.
  # However since this is a combination of anti-microbials that currently does
  # not exist as a separate concept, every SDD record will create three records
  # of the ingredients and the associated (manually added) quantity.
  declareTest(1105, "drug_exposure SDD")
  add_admissions(patientid = 1105, admissionid = 11105)
  add_drugitems(
    admissionid = 11105,
    ordercategoryid = 21,
    ordercategory = "Niet iv Antimicrobiele middelen",
    itemid = 8268,
    item = "SDD drank (4 x dgs)",
    isadditive = "0",
    isconditional = "0",
    rate = NULL,
    rateunit = NULL,
    rateunitid = NULL,
    ratetimeunitid = NULL,
    doserateperkg = 0,
    dose = 10,
    doseunit = "ml",
    doserateunit = NULL,
    doseunitid = 6,
    doserateunitid = NULL,
    administered = 10,
    administeredunit = "ml",
    administeredunitid = 6,
    action = "Nieuwe toediening",
    start = "16020000",
    stop = "16080000",
    duration = "1",
    solutionitemid = NULL,
    solutionitem = NULL,
    solutionadministered = NULL,
    solutionadministeredunit = NULL,
    fluidin = 10,
    iscontinuous = 0)

  # tobramycine
  expect_drug_exposure(
    person_id = 1105,
    drug_concept_id = 902722,
    quantity = "80"
    )

  # colistin
  expect_drug_exposure(
    person_id = 1105,
    drug_concept_id = 901845,
    quantity = "100"
    )


  # amphotericine B
  expect_drug_exposure(
    person_id = 1105,
    drug_concept_id = 1717240,
    quantity = "500"
    )

  ### Device_exposure ###
  declareTest(1201, "device_exposure person_id")
  add_admissions(patientid = 1201, admissionid = 11201)
  add_processitems(admissionid = 11201)

  declareTest(1202, "device_exposure mapping endotracheal tube")
  add_admissions(patientid = 1202, admissionid = 11202)
  add_processitems(admissionid = 11202, itemid = 12634)
  expect_device_exposure(person_id = 1202, device_concept_id = 4097216)

  # checks whether the quantity value based on the source_to_value_map
  # table is populated correctly
  declareTest(1203, "device_exposure quantity Trilumen Subclavia")
  add_admissions(patientid = 1203, admissionid = 11203)
  add_processitems(
    admissionid = 11203,
    itemid = 9167,
    item = "Trilumen Subclavia",
    start = 0,
    stop = 54060000
    )

  expect_device_exposure(
    person_id = 1203,
    device_concept_id = 4179206,
    quantity = 3,
    device_source_value = "Trilumen Subclavia"
  )

  ### Specimen ###
  declareTest(1301, "specimen person_id")
  add_admissions(patientid = 1301, admissionid = 11301)
  add_processitems(admissionid = 11301)
  add_freetextitems(admissionid = 11301, itemid = 11646, value = 'ART.')
  expect_specimen(person_id = 1301)

  declareTest(1302, "specimen mapping freetextitems ART.")
  add_admissions(patientid = 1302, admissionid = 11302)
  add_freetextitems(admissionid = 11302, itemid = 11646, value = 'ART.')
  expect_specimen(person_id = 1302,
                  specimen_concept_id = 4047496, # arterial blood specimen
                  specimen_type_concept_id = 32856 # Lab
                  )

  # Inserts test data into the AmsterdamUMCdb test tables
  log_info("Inserting test data into AmsterdamUMCdb test tables...")
  insert_sql <- paste(generateInsertSql(databaseSchema = "@amsterdamumcdb_schema"),
                      collapse = "\n")
  DatabaseConnector::renderTranslateExecuteSql(
    connection = adb_conn,
    sql = insert_sql,
    amsterdamumcdb_schema = amsterdaumcdb_test_schema
  )

  log_info("Running ETL...")

  # runs the ETL but without re-creating the vocabularies,
  # running Achilles or DataQualityDashboard
  etl(vocabulary = FALSE, mappings = TRUE,
      achilles = FALSE, dqd = FALSE)

  # Run checks based on records created by ETL
  log_info("Checking output...")
  test_sql <- paste(generateTestSql(databaseSchema = "@cdm_schema"),
                   collapse = "\n")

  DatabaseConnector::renderTranslateExecuteSql(
    connection = cdm_conn,
    sql = test_sql,
    cdm_schema = cdm_test_schema
  )

  # Get test results
  test_results_sql <- "SELECT * FROM @cdm_schema.test_results"
  test_results <- DatabaseConnector::renderTranslateQuerySql(
    connection = cdm_conn,
    sql = test_results_sql,
    cdm_schema = cdm_test_schema
  )

  for(i in 1:nrow(test_results)) {
    log_info(paste0(
      '\nTest ',
      test_results[i, 'ID'],
      '-',
      test_results[i, 'DESCRIPTION'],
      ':'
    ))
    status <- test_results[i, 'STATUS']
    expect_equal(status, 'PASS')
  }
})


