-- inserts body weight and height from admissions into stem_table
INSERT INTO @cdm_schema.stem_table
(
    domain_id,
    --id,
    person_id,
    concept_id,
    start_date,
    start_datetime,
    end_date,
    end_datetime,
    type_concept_id,
    provider_id,
    visit_occurrence_id,
    visit_detail_id,
    source_value,
    source_concept_id,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_concept_id,
    value_source_value,
    unit_source_concept_id,
    unit_source_value,
    verbatim_end_date,
    days_supply,
    dose_unit_source_value,
    modifier_concept_id,
    modifier_source_value,
    measurement_time,
    operator_concept_id,
    quantity,
    range_low,
    range_high,
    stop_reason,
    refills,
    sig,
    route_concept_id,
    route_source_value,
    lot_number,
    unique_device_id,
    production_id,
    anatomic_site_concept_id,
    disease_status_concept_id,
    specimen_source_id,
    anatomic_site_source_value,
    disease_status_source_value,
    condition_status_concept_id,
    condition_status_source_value,
    qualifier_concept_id,
    qualifier_source_value,
    event_id,
    event_field_concept_id
)
--admission weight
SELECT
    --Measurement
    21 AS domain_id,
    --id,
    a.patientid AS person_id,
    CASE a.weightsource
      WHEN 'Geschat' THEN 3026600 --Body weight Estimated
      WHEN 'Gemeten' THEN 3013762 --Body weight Measured
      WHEN 'Anamnestisch' THEN  3023166 --Body weight Stated
      ELSE 3025315 --Body weight
    END AS concept_id,
    DATE(a.admissiondatetime) AS start_date,
    a.admissiondatetime AS start_datetime,
    NULL AS end_date,
    NULL AS end_datetime,
    32818 AS type_concept_id, --EHR administration record
    NULL AS provider_id,
    a.admissionid AS visit_occurrence_id,
    NULL AS visit_detail_id,
    'weight' AS source_value,
    NULL AS source_concept_id,
    a.weight as value_as_number,
    NULL AS value_as_string,
    NULL AS value_as_concept_id,
    NULL AS unit_concept_id,
    a.weightgroup AS value_source_value,
    9529 AS unit_source_concept_id, --kilogram
    'kg' AS unit_source_value,
    NULL AS verbatim_end_date,
    NULL AS days_supply,
    NULL AS dose_unit_source_value,
    NULL AS modifier_concept_id,
    NULL AS modifier_source_value,
    NULL AS measurement_time,
    NULL AS operator_concept_id,
    NULL AS quantity,
    NULL AS range_low,
    NULL AS range_high,
    NULL AS stop_reason,
    NULL AS refills,
    NULL AS sig,
    NULL AS route_concept_id,
    NULL AS route_source_value,
    NULL AS lot_number,
    NULL AS unique_device_id,
    NULL AS production_id,
    NULL AS anatomic_site_concept_id,
    NULL AS disease_status_concept_id,
    NULL AS specimen_source_id,
    NULL AS anatomic_site_source_value,
    NULL AS disease_status_source_value,
    NULL AS condition_status_concept_id,
    NULL AS condition_status_source_value,
    NULL AS qualifier_concept_id,
    NULL AS qualifier_source_value,
    NULL AS event_id,
    NULL AS event_field_concept_id
FROM @cdm_schema.admissions_scalar a
WHERE NOT a.weight IS NULL
ORDER BY a.admissionid
;
--admission height
INSERT INTO @cdm_schema.stem_table
(
    domain_id,
    --id,
    person_id,
    concept_id,
    start_date,
    start_datetime,
    end_date,
    end_datetime,
    type_concept_id,
    provider_id,
    visit_occurrence_id,
    visit_detail_id,
    source_value,
    source_concept_id,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_concept_id,
    value_source_value,
    unit_source_concept_id,
    unit_source_value,
    verbatim_end_date,
    days_supply,
    dose_unit_source_value,
    modifier_concept_id,
    modifier_source_value,
    measurement_time,
    operator_concept_id,
    quantity,
    range_low,
    range_high,
    stop_reason,
    refills,
    sig,
    route_concept_id,
    route_source_value,
    lot_number,
    unique_device_id,
    production_id,
    anatomic_site_concept_id,
    disease_status_concept_id,
    specimen_source_id,
    anatomic_site_source_value,
    disease_status_source_value,
    condition_status_concept_id,
    condition_status_source_value,
    qualifier_concept_id,
    qualifier_source_value,
    event_id,
    event_field_concept_id
)
SELECT
    21 AS domain_id,  --Measurement
    --id,
    a.patientid AS person_id,
    CASE  heightsource
      WHEN 'Geschat' THEN 3035463 --Body height Estimated
      WHEN 'Gemeten' THEN 3023540 --Body height Measured
      WHEN 'Anamnestisch' THEN 3019171 --Body height Stated
      ELSE 3036277 --Body height
    END AS concept_id,
    DATE(a.admissiondatetime) AS start_date,
    a.admissiondatetime AS start_datetime,
    NULL AS end_date,
    NULL AS end_datetime,
    32818 AS type_concept_id,  --EHR administration record
    NULL AS provider_id,
    a.admissionid AS visit_occurrence_id,
    NULL AS visit_detail_id,
    'height' AS source_value,
    NULL AS source_concept_id,
    a.height as value_as_number,
    NULL AS value_as_string,
    NULL AS value_as_concept_id,
    NULL AS unit_concept_id,
    a.heightgroup AS value_source_value,
    8582 AS unit_source_concept_id, --centimeter
    'cm' AS unit_source_value,
    NULL AS verbatim_end_date,
    NULL AS days_supply,
    NULL AS dose_unit_source_value,
    NULL AS modifier_concept_id,
    NULL AS modifier_source_value,
    NULL AS measurement_time,
    NULL AS operator_concept_id,
    NULL AS quantity,
    NULL AS range_low,
    NULL AS range_high,
    NULL AS stop_reason,
    NULL AS refills,
    NULL AS sig,
    NULL AS route_concept_id,
    NULL AS route_source_value,
    NULL AS lot_number,
    NULL AS unique_device_id,
    NULL AS production_id,
    NULL AS anatomic_site_concept_id,
    NULL AS disease_status_concept_id,
    NULL AS specimen_source_id,
    NULL AS anatomic_site_source_value,
    NULL AS disease_status_source_value,
    NULL AS condition_status_concept_id,
    NULL AS condition_status_source_value,
    NULL AS qualifier_concept_id,
    NULL AS qualifier_source_value,
    NULL AS event_id,
    NULL AS event_field_concept_id
FROM @cdm_schema.admissions_scalar a
WHERE NOT a.height IS NULL
ORDER BY a.admissionid

